Update UserGuide.md
AY2223S1-CS2103T-T17-1/tp pull request #148
Opened 2022-11-02 12:45 UTC by yellow-294

2022-11-02 16:28 UTC, vantemoon reviewed
Other issues related to case sensitivity that can be added:
1. Positions are case-insensitive
2. Availabilities are case-insensitive
3. Roles are case-insensitive

Regarding issue #138, can add "grades should be in the format [integer]/[integer] in the grade command section.

2022-11-02 16:50 UTC, cxyterence approved these changes
LGTM, but add on to above comments

2022-11-04 13:30 UTC, guowei42 requested changes
other than the one part commented below LGTM

2022-11-04 13:30 UTC, guowei42 commented on docs/UserGuide.md
> +Adds a new contact with the provided details. Required fields include name, phone number, email, position, and tag. Tags represent the module and tutorial group a person is associated with and must b
I think should add address is required field as well

2022-11-04 17:03 UTC, yellow-294 commented
Respective changes have been made, thanks everyone.

2022-11-05 09:54 UTC, guowei42 approved these changes

2022-11-06 14:06 UTC, merged